title: ControlZ  DevTeam Guides
description: Guias para os integrantes do DevTeam iniciantes!
theme: just-the-docs

url: https://controlz-devteam.github.io/Guide/

aux_links:
  "Repositório do Guia":
    - https://github.com/ControlZ-DevTeam/Guide

#nav_external_links:
#  - title: Repositório do Guia
#    url: https://github.com/ControlZ-DevTeam/Guide

aux_links_new_tab: true

color_scheme: dark

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

mermaid:
  version: "9.1.6"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: yellow
  new:
    title: Novo
    color: green
  note:
    title: "Obs:"
    color: purple
  warning:
    title: Avivo
    color: red
